# Generated by Django 6.0.2 on 2026-04-28 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Максимальное кол-во участников')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'События',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'день недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('student', 'Учащийся'), ('parent', 'Родитель'), ('organizer', 'Организатор')], default='student', max_length=63, verbose_name='Роль')),
                ('surname', models.CharField(max_length=63, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=63, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=63, verbose_name='Отчество')),
                ('phone', models.CharField(unique=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.baseevent')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
            ],
            bases=('website.baseevent',),
        ),
        migrations.AddField(
            model_name='baseevent',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('baseevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.baseevent')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'кружок',
                'verbose_name_plural': 'Кружки',
            },
            bases=('website.baseevent',),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_date', models.DateField(blank=True, null=True, verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('finish_time', models.TimeField(blank=True, null=True, verbose_name='Время конца')),
                ('place', models.CharField(verbose_name='Место проведения')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.weekday', verbose_name='День недели')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'участника',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
