# Generated by Django 6.0 on 2026-01-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(unique=True, verbose_name='Номер телефона'),
        ),
    ]
