# Generated by Django 6.0 on 2026-02-10 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_customuser_photo_alter_customuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('capacity', models.IntegerField(verbose_name='Максимальное кол-во участников')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'день недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('finish_time', models.TimeField(verbose_name='Время конца')),
                ('place', models.CharField(verbose_name='Место проведения')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.event', verbose_name='Событие')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.weekday', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.event')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'кружок',
                'verbose_name_plural': 'Кружки',
            },
            bases=('website.event',),
        ),
    ]
