# Generated by Django 6.0 on 2026-02-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_event_weekday_schedule_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Превью'),
        ),
    ]
